### ISSUE TITLE
Truncated messages

### ISSUE THREAD

**Issue by aattieh** [WebexSamples/hookbuster#5]
Hi team, I have noticed that when using hookbuster if a webhook being received with a payload more than 1 MB the internal HTTP POST would have the JSON content as truncated which is triggering an exception in backend code, so is this a known issue ? this is happening mostly when my BOT is sending messages into some space the webhook comes for the BIT messages.

**Comment by jbenyovs** [comment]
@aattieh this is not a known issue. Can you be a bit more specific with the steps on how to reproduce this? How big is the message, does it have any attachments, do you have the exact error, at what character gets the payload truncated (i.e. how long is the JSON that is still usable)?

**Comment by jbenyovs** [comment]
Closing this due to lack of response and not being able to reproduce it.
