### ISSUE TITLE
Issues in Listening for Events

### ISSUE THREAD

**Issue by karthikkumarb** [WebexSamples/hookbuster#6]
I have cloned and followed the same steps, looks like I am having an issue when running in two different machines.|

Not working machine logs
LoggerProxy->warn#NO LOGGER DEFINED
INFO: token authenticated as sushi

Working machine logs
LoggerProxy->warn#NO LOGGER DEFINED
INFO: token authenticated as sushi
INFO: Listening for events from the rooms resource
INFO: Registered handler to forward  rooms:created events
INFO: Registered handler to forward  rooms:updated events
INFO: Listening for events from the messages resource
INFO: Registered handler to forward  messages:created events
INFO: Registered handler to forward  messages:deleted events
INFO: Listening for events from the memberships resource
INFO: Registered handler to forward  memberships:created events
INFO: Registered handler to forward  memberships:updated events
INFO: Registered handler to forward  memberships:deleted events
INFO: Listening for events from the attachmentActions resource
INFO: Registered handler to forward  attachmentActions:created events

**Comment by jbenyovs** [comment]
@karthikkumarb can you please describe your scenario in more details? Why are you running the same app with the same user on 2 different machines? Registering the user is happening on server side, not locally, so you should only ever need to register with the same user on one machine.

**Comment by jbenyovs** [comment]
@karthikkumarb since I have not heard back from you for a long time, closing this issue, as I assume it is not reproducible anymore. Thanks
